services:
  - type: web
    name: smart-license-verifier
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: streamlit run license_verification_app.py --server.port=10000
    envVars:
      - key: PORT
        value: 10000
